#!/bin/bash


#clean up previous job (just in case)
rm -f finished

module load singularity 2> /dev/null

echo "starting main"

#singularity exec -e docker://brainlife/normalizedata
singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./msa/main


#export MATLABPATH=$MATLABPATH:$SERVICE_DIR
#time matlab -nodisplay -nosplash -r main

#check for output files
if [ -s dwi.bvecs ] && [ -s dwi.bvals ]; then
	echo 0 > finished
else
	echo "bvecs or bvals  missing"
	echo 1 > finished
	exit 1
fi

